po# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DMCA-Admin' do
#pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
#pod 'AlamofireImage'
pod 'KOActivityIndicator'
pod 'ReachabilitySwift'
pod 'Localize-Swift'
pod 'UIColor_Hex_Swift'
pod 'ENSwiftSideMenu'
pod 'KMPlaceholderTextView'
pod 'Dollar'
pod 'Cent'
end

target 'DMCA-AdminTests' do

end

target 'DMCA-AdminUITests' do

end

